apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-staff-to-internal
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: gsx-app # Allow devs to Node
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.100.0/24
      ports:
        - protocol: TCP
          port: 3000
---

