apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-public-to-nginx
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: nginx-gsx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0 # Anyone
      ports:
        - protocol: TCP
          port: 8080
